# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MovieStore' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MovieStore
  pod 'Alamofire', :git => 'https://github.com/Alamofire/Alamofire.git'
  pod 'Kingfisher', :git => 'https://github.com/onevcat/Kingfisher.git'
  pod 'ESPullToRefresh', :git => 'https://github.com/eggswift/pull-to-refresh.git'
  pod 'FMDB'
  pod 'SWRevealViewController'
  pod 'SwiftyJSON'

  target 'MovieStoreTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MovieStoreUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
